import React from "react"
import type { Metadata } from "next"
import "./globals.css"
import { ThemeProvider } from "@/components/providers/NextThemeProvider"
import { NotificationBar } from "@/components/customs/NotificationBar"
import { IBM_Plex_Sans_Thai } from "next/font/google"
import { cn } from "@/lib/utils"

const IBMPlexSansTH = IBM_Plex_Sans_Thai({
  subsets: ["latin", "thai"],
  display: "swap",
  weight: ["100", "200", "300", "400", "500", "600", "700"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning>
      <body className={cn(IBMPlexSansTH.className, "")}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem>
          <NotificationBar isShow />
          {children}
        </ThemeProvider>
      </body>
    </html>
  )
}
