name: Trip CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [18.20.4]
        pnpm-version: [9.12.0]

    env:
      SECRET: ${{ secrets.NEXT_PUBLIC_SECRET }}
      GOOGLE_CLIENT_ID: ${{ secrets.NEXT_PUBLIC_GOOGLE_CLIENT_ID }}
      GOOGLE_CLIENT_SECRET: ${{ secrets.NEXT_PUBLIC_GOOGLE_CLIENT_SECRET }}
      FIREBASE_PROJECT_ID: ${{ secrets.NEXT_PUBLIC_FIREBASE_PROJECT_ID }}
      FIREBASE_CLIENT_EMAIL: ${{ secrets.NEXT_PUBLIC_FIREBASE_CLIENT_EMAIL }}
      FIREBASE_PRIVATE_KEY: ${{ secrets.NEXT_PUBLIC_FIREBASE_PRIVATE_KEY }}
      FIREBASE_API_KEY: ${{ secrets.NEXT_PUBLIC_FIREBASE_API_KEY }}
      FIREBASE_AUTH_DOMAIN: ${{ secrets.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN }}
      FIREBASE_STORAGE_BUCKET: ${{ secrets.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET }}
      FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID }}
      FIREBASE_APP_ID: ${{ secrets.NEXT_PUBLIC_FIREBASE_APP_ID }}
      RESEND_API_KEY: ${{ secrets.NEXT_PUBLIC_RESEND_API_KEY }}
      RESEND_EMAIL_FROM: ${{ secrets.NEXT_PUBLIC_RESEND_EMAIL_FROM }}
      BASE_URL: ${{ secrets.NEXT_PUBLIC_BASE_URL }}

    steps:
      - name: Action checkout
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Use pnpm ${{ matrix.pnpm-version }}
        uses: pnpm/action-setup@v3
        with:
          version: ${{ matrix.pnpm-version }}

      - name: Install dependencies
        run: pnpm install

      - name: Build project
        run: pnpm run build

      - name: Go to directory
        run: cd /home/ubuntu/triptiaopao.com/actions-runner/_work/repositories/triptiaopao

      - name: Setup secret environments
        run: |
          pm2 set triptiaopao:NEXT_PUBLIC_SECRET ${{ env.SECRET }}
          pm2 set triptiaopao:NEXT_PUBLIC_GOOGLE_CLIENT_ID ${{ env.GOOGLE_CLIENT_ID }}
          pm2 set triptiaopao:NEXT_PUBLIC_GOOGLE_CLIENT_SECRET ${{ env.GOOGLE_CLIENT_SECRET }}
          pm2 set triptiaopao:NEXT_PUBLIC_FIREBASE_PROJECT_ID ${{ env.FIREBASE_PROJECT_ID }}
          pm2 set triptiaopao:NEXT_PUBLIC_FIREBASE_CLIENT_EMAIL ${{ env.FIREBASE_CLIENT_EMAIL }}
          pm2 set triptiaopao:NEXT_PUBLIC_FIREBASE_PRIVATE_KEY ${{ env.FIREBASE_PRIVATE_KEY }}
          pm2 set triptiaopao:NEXT_PUBLIC_FIREBASE_API_KEY ${{ env.FIREBASE_API_KEY }}
          pm2 set triptiaopao:NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN ${{ env.FIREBASE_AUTH_DOMAIN }}
          pm2 set triptiaopao:NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET ${{ env.FIREBASE_STORAGE_BUCKET }}
          pm2 set triptiaopao:NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID ${{ env.FIREBASE_MESSAGING_SENDER_ID }}
          pm2 set triptiaopao:NEXT_PUBLIC_FIREBASE_APP_ID ${{ env.FIREBASE_APP_ID }}
          pm2 set triptiaopao:NEXT_PUBLIC_RESEND_API_KEY ${{ env.RESEND_API_KEY }}
          pm2 set triptiaopao:NEXT_PUBLIC_RESEND_EMAIL_FROM ${{ env.RESEND_EMAIL_FROM }}
          pm2 set triptiaopao:NEXT_PUBLIC_BASE_URL ${{ env.BASE_URL }}

      - name: Restart pm2 environments
        run: |
          pm2 restart triptiaopao --watch ||
          pm2 start pnpm --name triptiaopao -- start --update-env
